###   Crear Curso
POST http://localhost:5000/courses HTTP/1.1
content-type: application/json

{
  "nombre": "Aprende a jugar minecraft",
  "descripcion": "Curso completo para aprender Minecraft desde cero.",
  "imagen_principal": "foto1.jpg",
  "imagen_detalle": "foto2.jpg",
  "valoraciones": [],
  "valoracion_promedio": 0,
  "comentarios": [],
  "participantes": 0,
  "inscritos":[],
  "unidades": [
    {
      "nombre": "Mesa de crafteo",
      "orden": 1,
      "clases": [
        {
          "nombre": "Talando arboles",
          "descripcion": "Aprende a talar arboles",
          "video_url": "https://youtube.com/Java.mp4",
          "archivos_adjuntos": ["introduccion.pdf"],
          "orden": 1,
          "comentarios": []
        },
        {
          "nombre": "Creando mesa de crafteo",
          "descripcion": "Aprende a crear una mesa de crafteo.",
          "video_url": "https://youtube.com/ciclos.mp4",
          "archivos_adjuntos": ["mesa.pdf"],
          "orden": 2,
          "comentarios": []
        }
      ]
    }
  ]
}



###   Obtener Cursos
GET http://localhost:5000/courses HTTP/1.1


###Obtener Curso por ID
GET http://localhost:5000/courses/6722df416c158ac18588c98f HTTP/1.1



### Registrar Usuarios
POST http://localhost:5000/courses/6722df416c158ac18588c98f/register
content-type: application/json

{
  "user_id":"6718652142e1d60488dc0bed"
}
