###   Crear Curso
POST http://localhost:5000/courses HTTP/1.1
content-type: application/json

{
  "nombre": "Curso 1",
  "descripcion": "Este es el primer Curso.",
  "imagen_principal": "foto1.jpg",
  "imagen_detalle": "foto2.jpg",
  "valoraciones": [],
  "valoracion_promedio": 0,
  "comentarios": [],
  "participantes": 0,
  "inscritos":[],
  "unidades": [
    {
      "nombre": "Unidad 1",
      "orden": 1,
      "clases": [
        {
          "nombre": "clase 1",
          "descripcion": "Descripcion de la clase 1",
          "video_url": "https://youtube.com/clase1.mp4",
          "archivos_adjuntos": ["introduccion.pdf"],
          "orden": 1,
          "comentarios": []
        },
        {
          "nombre": "Clase 2",
          "descripcion": "Descripcion de la clase 2",
          "video_url": "https://youtube.com/clase2.mp4",
          "archivos_adjuntos": ["clase2.pdf"],
          "orden": 2,
          "comentarios": []
        }
      ]
    }
  ]
}





###   Obtener Cursos
GET http://localhost:5000/courses HTTP/1.1


###Obtener Curso por ID
GET http://localhost:5000/courses/6727d1b7fa9a003b933bd6e4 HTTP/1.1



### Registrar Usuarios
POST http://localhost:5000/courses/6727d1b7fa9a003b933bd6e4/register
content-type: application/json

{
  "user_id":"6727cd5519bd43e5ce479a63"
}
