# Crear tabla
POST http://localhost:5000/dynamodb/create_table
Content-Type: application/json

### Agregar usuario
POST http://localhost:5000/dynamodb/add_user
Content-Type: application/json

{
  "username": "user123",
  "password": "12345"
}

####obtener usuarios
GET http://localhost:5000/dynamodb/users

### Obtener usuario
GET http://localhost:5000/dynamodb/get_user/juan@gmail.com


### Inscribir usuario en un curso
POST http://localhost:5000/dynamodb/enroll_user
Content-Type: application/json

{
  "username": "juan@gmail.com",
  "course_id": "6755cf0f0d56739c787712f1"  
}

### Obtener Cursos de un usuario  
GET http://localhost:5000/dynamodb/get_user_courses?username=testuser

### Obtener login
POST http://localhost:5000/dynamodb/login
Content-Type: application/json

{
  "username": "user123",
  "password": "12345"
}