# Crear tabla
POST http://localhost:5000/dynamodb/create_table
Content-Type: application/json

### Agregar usuario
POST http://localhost:5000/dynamodb/add_user
Content-Type: application/json

{
  "username": "aaa1",
  "password": "12345"
}

### Obtener usuario
GET http://localhost:5000/dynamodb/get_user/testuser


### Inscribir usuario en un curso
POST http://localhost:5000/dynamodb/enroll_user
Content-Type: application/json

{
  "username": "testuser",
  "course_id": "6755cf0f0d56739c787712f1"  
}

###
GET http://localhost:5000/dynamodb/get_user_courses?username=testuser

### Obtener login
POST http://localhost:5000/dynamodb/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "12345"
}