###comentario Curso
POST http://localhost:5000/courses/6722df416c158ac18588c98f/comment
Content-Type: application/json

{
  "title": "AAA",
  "id_user": "6718652142e1d60488dc0bed",
  "content": "Curso excelente y bien explicado.",
  "likes": 5,
  "dislikes": 2
}   


###comentario Clase
POST http://localhost:5000/classes/6722df426c158ac18588c991/comment
Content-Type: application/json

{
  "title": "Mala clase",
  "id_user": "6718652142e1d60488dc0bed",
  "content": "No entendi nada de la clase.",
  "likes": 5,
  "dislikes": 2
}   
